--- 
format: 1
handler: 
  commit: 362837f568d14098835d8ff8baafc8461a8c775e
  branch: master
lock: false
repository_class: Piston::Git::Repository
repository_url: git@github.com:chillu/opensearchclient.git
