infrastructure: ^3
php_settings:
  version: 7.3
  cli:
    max_execution_time: 0
shared_dirs:
  mysite:
    data: {}
    htdocs: {}
crons:
  mytask:
    time: "0 3 * * *"
    command: "/var/www/mysite/www/makedoc.sh | logger -t SilverStripe_cron"
url_rules:
  mysite:
    - '^.*': 'apache'
